---
#################################
#Playbook of Hosts linux file update#
#################################
- name: Transfer the script
  copy: 
    src: /etc/ansible/roles/update-host-file/files/ 
    dest: /tmp 
    mode: 0755

- name: Execute the script
  shell: sudo cd /tmp && sudo sh /tmp/add-ipnodes-hosts.sh
   
- name: Ansible delete multiple file example
  shell: sudo rm -rf /tmp/add-ipnodes-hosts.sh && sudo rm -rf /tmp/node-ip.txt 
